inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/dummy/**/*'

RSpec/ExampleLength:
  Max: 200

Metrics/MethodLength:
  Max: 60

Metrics/BlockLength:
  Max: 200

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false