version: "3"
services:
  db:
    image: postgis/postgis
    ports:
      - "5577:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"

