source 'https://rubygems.org'

ruby '2.7.5'

gem 'rails', '~> 6.1.4', '>= 6.1.4.4'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "pg", "~> 1.3"
gem "activerecord-postgis-adapter", "~> 7.1"
